systopia/de.systopia.remoteevent

Civi/RemoteParticipant/Event/GetCancelParticipantFormEvent.php, Civi/RemoteParticipant/Event/GetCreateParticipantFormEvent.php, Civi/RemoteParticipant/Event/GetParticipantFormEventBase.php, Civi/RemoteParticipant/Event/GetUpdateParticipantFormEvent.php, Civi/RemoteParticipant/Event/UpdateEvent.php, api/v3/RemoteParticipant/GetForm.php, remoteevent.php
Confirming/rejecting participant invitations are only working when using the `RemoteParticipant.create` API (with invitation tokens), not with `RemoteParticipant.update`, while it technically is an update.
Also, confirming/rejecting invitations is not possible when the contact has no permission to register (anymore), e.g. because the registration period has expired or the event is locked for new registrations, while invitations should still be processed.
This PR allows invitation confirmation front-ends to use both API endpoints for processing invitations.
Technical details:
* The `RemoteParticipant.get_form` API now adds the *Confirm*/*Reject* field for the `update` context
* All involved APIs now check the token for all allowed contexts (`invite` and `update` for the `update` API)
* The …
=> Allow invitations to also use the "update" form

CRM/Remoteevent/EventLocation.php
Avoids errors with `FULL_GROUP_BY` SQL mode enabled when dealing with alternative event locations
=> Disable Full Group By SQL mode for incompatible event location queries

templates/CRM/Remoteevent/Form/EventSessions.tpl
edit EventSessions.tpl
- change css-class of thead`s first row
the theme "Shoreditch" is overwriting <th> elements like this with a white background, which results in white text being invisible.
I therefor suggest to use a base-css-class with non-white font-color like "column-header".
=> [EKIR PHASE II] #20024

Civi/RemoteParticipant/Event/GetCreateParticipantFormEvent.php, Civi/RemoteParticipant/Event/GetUpdateParticipantFormEvent.php
This fixes issues with the *Accept Invitation* field not being the first field in the form when there are fields with lower weights (i.e. lower than ist current weight of `10`). This is especially the case when using the [remoteeventformeditor](https://github.com/systopia/remoteeventformeditor) extension for defining profile fields.
Also, this field should be required for not showing a *- Select -* option.
Special eye should be kept on whether the now negative weight of `-10` is handled correctly.
*systopia-reference: 22749*
=> Define "confirm" field for event invitations with lower weight and as required

CRM/Remoteevent/EventFlags.php, tests/phpunit/CRM/Remoteevent/RegistrationTest.php
There's already a `can_register` flag, which supposedly returns `1` for events that are fully booked but have a waiting list, which events also have a flag for, `has_waitlist`. But there's no flag indicating whether the waiting list is active (i.e. the event is fully booked and new participants are to be added to the waitlist).
@bjendres would you be able to line out what else needs to be done for this, apart from what I drafted?
*systopia-reference: 22809*
=> Add `has_active_waitlist` flag to events

api/v3/RemoteEvent/Get.php
When calling `RemoteEvent.get` with the `id` parameter set to the event ID, the event ID is currently being ignored due to `\CRM_Remoteevent_RemoteEvent::deriveEventID()` only looking for the`event_id` parameter.
This leads to all participant objects being queried with `Participant.get` in `\Civi\RemoteEvent::getParticipantID()` which will yield potentially incorrect values, as this API call limits to 1 result and passes `0` as `event_id`.
I'm not sure how this could have been working at all …
(Plus, passing `event_id=0` for the `Participant.get` API takes a code path that generates [invalid SQL in Core](https://github.com/civicrm/civicrm-core/blob/99553cb4f5556abb416b4325f9d34d42cf25df05/CRM/Event/BAO/Event.php#L279-L286) (`Incorrect DATETIME value ''`) (at least with MySQL 8 on my local …
=> Translate event ID in`RemoteEvent.get` with `id` parameter

CRM/Remoteevent/Registration.php, CRM/Remoteevent/RegistrationProfile.php, CRM/Remoteevent/RegistrationUpdate.php, Civi/RemoteParticipant/Event/RegistrationEvent.php, Civi/RemoteParticipant/Event/Util/ParticipantFormEventUtil.php, Civi/RemoteParticipant/RegistrationEventFactory.php, api/v3/RemoteParticipant/Create.php, remoteevent.php
This change allows to use names for form fields different to the entity field names. Additionally it's now possible to specify value callbacks in the field spec (e.g. if the form field value is combined of two values for the dependent field functionality).
This fixes also loading of country_id and state_province_id (see code comments for details.)
systopia-reference: 23402
=> Allow to specify entity field name in field spec

api/v3/RemoteParticipant/Create.php
Fixes error introduced by PR #60.
=> Fix method call in `civicrm_api3_remote_participant_create()`

info.xml
Because `ParticipantStatusType` is used the minimal CiviCRM version has to be increased to 5.61.
https://github.com/systopia/de.systopia.remoteevent/blob/22a87ea70b5c1c61931ae0e4dba0638b1c0e629b/CRM/Remoteevent/RemoteEvent.php#L343
=> Increase minimal CiviCRM version to 5.61

Civi/RemoteParticipant/Event/GetParticipantFormEventBase.php
This prevents that calling `setPrefillValue()` with a field name not available creates an incomplete form field spec.
=> GetParticipantFormEventBase: Set prefill values only for fields available in the result

CRM/Remoteevent/RegistrationProfile/Standard2.php
This profile only uses Contact entity fields, which can be prepopulated with the generic super method added with #60.
This also allows for profiles inheriting from "Standard2" to use custom fields on Contact and Participant entities without writing their own implementation of the method.
=> Use super method for providing default values in "Standard2" profile

Civi/RemoteEvent.php, Civi/RemoteParticipant/Event/RegistrationEvent.php, Civi/RemoteParticipant/RegistrationEventFactory.php
… as otherwise for profiles that submit the `role_id` (e. g. in an invitation confirmation), the default role would always be used.
NB: I rebased the branch, effectively re-implementing the fix, as the underlying structure changed with #60, thus asking @dontub for a review.
=> Only assign default participant role for new participants

CRM/Remoteevent/Localisation.php
This hasn't been implemented yet, so localization only "works" for the default language (uses just `E::ts()`).
This makes it effectively impossible to have English labels when your CiviCRM's default language is not English.
This PR makes the locale be set globally before calling `E::ts()` and resets it afterwards. However, I'm not sure about possible side effects.
~~I consider this a bug, so set the milestone to `1.1` which is currently in beta and could receive bug fixes. If someone thinks this is too much of a change for beta, this will need to be postponed to `1.2` instead, which is currently in alpha.~~
*systopia-ref: 24106*
=> Make localisation actually work

CRM/Remoteevent/Upgrader.php, resources/custom_group_alternative_location.json, resources/custom_group_remote_registration.json
Edit: In contrast to the initial claim, this doesn't fix the problem with custom field values reset on the Information tab of the event form https://lab.civicrm.org/dev/core/-/issues/5238
Nevertheless, I think this change makes sense.
systopia-reference: 25017
=> Make custom groups reserved

CRM/Remoteevent/Localisation.php
This should drastically improve performance for localized remote event forms with many fields/many field options.
Testing should involve a requested locale different from the current default locale (i.e. CiviCRM running in English, requested locale being another language).
This makes use of some code copied from Core's `ts()` function to make it work with locales other than the current default one.
Since localization might get very slow, this should be cherry-picked for the `1.2.x` branch as well.
*systopia-reference: 25219*
=> Refactor localization for not changing UF locale for each string

CRM/Remoteevent/RegistrationProfile.php, Civi/RemoteParticipant/RegistrationEventFactory.php
#60 refactored the way fields on contacts and participants are being processed during event registrations, including additional participants. This introduced a regression resulting in additional participants not being registered at all due to
* a missing condition for early-returning during calculation of additional participants' data
* missing entity field names (i.e. stripping `additional_x_` from each field name)
This will have to be merged into `1.2.x` as well.
=> Fix regression causing additional participants not being registered

CRM/Remoteevent/RegistrationProfile.php
Otherwise registering additional participants fails with fields having `entity_field_name` different than their profile form name.
*systopia-reference: 24534*
=> Use correct entity field names for additional participant fields

CRM/Remoteevent/EventFlags.php, CRM/Remoteevent/Registration.php, CRM/Remoteevent/RegistrationProfile.php, CRM/Remoteevent/RemoteEvent.php, api/v3/RemoteEvent/Get.php
The number returned by `Registration::getRegistrationCount()` previously counted only 'Positive' registrations *with* active count flag. Having the count flag makes it counterintuitive if the default doesn't count all registrations with active count flag.
This assumption was obviously made when the waitlist feature was implemented which currently doesn't behave as expected.
I've checked the calls of `Registration::getRegistrationCount()` and changed one call. Though I'm not quiet sure if it is correct. Please check the other calls of the method if adjustment is necessary.
systopia-reference: 25017
=> Count all registrations with active count flag by default

tests/phpunit/CRM/Remoteevent/IssuesTest.php
There is only a localization for `de_DE` but not `de`.
This PR makes the localization test pass. However, we should consider changing the localization detection so that not only `de_DE` works, but also `de`. Quick idea: Make a symlink from `de` to `de_DE` and adapt the code so `de` is used if `de_CH` was submitted as `locale` parameter. Though this is out of the scope of this PR.
=> IssuesTest: Use `de_DE` instead of `de` as `locale`

api/v3/RemoteEvent/Get.php, tests/phpunit/CRM/Remoteevent/TestBase.php
Operator `IN` is not possible in `RemoteEvent.get`.
=> TestBase: Fix method `getRemoteEvents`

tests/phpunit/CRM/Remoteevent/EventFlagsTest.php
The previous tests assumed that the operator `IN` is allowed in `RemoteEvent.get` which is not the case (anymore?).
=> EventFlagsTest: Fix `testFlagFilters`

CRM/Remoteevent/Form/Settings.php, Civi/RemoteParticipant/Event/GetCreateParticipantFormEvent.php, templates/CRM/Remoteevent/Form/Settings.hlp, templates/CRM/Remoteevent/Form/Settings.tpl
This adds a general setting for *CiviRemote Event* for changing the pre-selected option for the *Confirm Invitation* field which is part of forms for participants with the status *Invited*.
Previously, there was no default value for this field, which, in the *CiviRemote Event* Drupal module, causes the pre-selected option to be "Decline Invitation" with all other fields of the form being hidden initially. This new option allows the pre-selected calue to be "Accept Invitation" and the entire form be displayed initially.
*systopia-reference: 26948*
=> Add setting for invitation confirm field default value

README.md, docs/api.md, docs/configuration.md, docs/extensibility.md, mkdocs.yml
The feature: "register additional participants" is already part of this documentation.
*systopia-reference: 24194*
=> Improve documentation

CRM/Remoteevent/Registration.php, Civi/RemoteParticipant/RegistrationEventFactory.php
Additional participants do not get the *Approval required* status when they should (and the primary participant does). Additional participants also do not get a registration date (as the primary participant does).
This PR sets the status (as is done for the primary participant via `\CRM_Remoteevent_Registration::determineParticipantStatus()`) and copies the registration date from the primary participant prior to creating the additional participant.
I'm not sure if a check for existing values or values in the submission is necessary here …
*systopia-reference: 26708*
=> Add participant status and registration date for additional participants

CRM/Remoteevent/Registration.php
When approval is required for registrations, excess participants currently won't be given the `On Waitlist` status, effectively not using an active waitlist.
This PR adds participants to the waitlist regardless of whether approval is required. This matches core behavior. Participants on the waitlist are considered to require approval anyway. I consider this a bug, thus no configuration option for keeping the current behavior necessary, as there is no reduced functionality with this change.
*systopia-reference: 27449*
=> Add participants to waitlist if approval required

CRM/Remoteevent/EventSessions.php, Civi/RenderEvent.php, resources/remote_session_description.tpl, resources/remote_session_short_description.tpl
The extension's utility method for rendering *Smarty* templates does not apply the Smarty User Content Policy introduced with CiviCRM `5.74.4` and `5.69.6`. Although rendering currently does not explicitly involve user content, it's safer to apply the policy and make default templates compatible by replacing usages of the `{crmAPI}` *Smarty* tag which is considered insecure by CiviCRM Core and thus causes an error with the policy applied.
There has been only one occurrence of the `{crmAPI}` *Smarty* tag in the extension's templates, which can be easily replaced by adding a template variable instead.
As which template is rendered is subject to Symfony event listener implementations, this PR should be included in a major (BC-breaking) or a minor version only with explicit documentation.
=> Apply Smarty Security Policy and replace usage of `{crmAPI}` in affected templates

CRM/Remoteevent/Form/RegistrationConfig.php
The selection of the global CiviRemote Event setting as XCM profile is stored as empty string. Though, the empty string isn't returned on APIv3 calls (anymore?). This results in the first profile in the select field being selected on form load. Therefore switching to APIv4 fixes this issue.
Additionally PHP type hints are added and the deprecated method `CRM_Utils_Array::value()` isn't used anymore.
systopia-reference: 29954
=> RegistrationConfig: Fix loading empty XCM profile (i.e. global setting)

Civi/Api4/RemoteEventMailingList.php, phpcs.xml.dist
The permission for `meta` actions should be set to `access CiviCRM` to avoid a `\Civi\API\Exception\UnauthorizedException` when calling the `getActions` action.
systopia-reference: 30501
=> Fix `meta` permissions in `RemoteEventMailingList`
